# Generated by Django 5.2 on 2025-11-27 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_marks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Marks",
        ),
    ]
