# Generated by Django 5.2 on 2025-11-27 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_delete_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Performance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_1",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "test_2",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "test_3",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="core.studentprofile",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "teacher")},
            },
        ),
    ]
